services:
  api:
    build:
      context: .
      target: development
    container_name: api-post
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
